apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: petdb
  MYSQL_DATABASE_URL: jdbc:mysql://mysql/petdb
  initdb.sql: |
    use petdb;
    CREATE TABLE pet (name VARCHAR(20), owner VARCHAR(20), species VARCHAR(20), sex CHAR(1), birth DATE, death DATE);
    INSERT INTO pet VALUES ('Puffball','Diane','hamster','f','1999-03-30',NULL);
